# ----
# Site

title: Diana Hanesová - art
url: "https://diana-hanesova-art.netlify.com"
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Diana Hanesova - Art portfolio
author:
  name: Diana Hanesova
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Diana Hanesova
  links:
    - https://github.com/filiphanes/diana-hanesova-art

# -----
# Build

timezone: Europe/Bratislava

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      text_width: true
      image: /uploads/abstrakcia-modro-biela.jpg
  -
    scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  image:
    width: 2048
    height: 1365
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true
